# ????
#   - trace ??????,????
#   - debug ?????????
#   - info ????????
#   - warn ??????????
#   - error ????????
#   - fatal ?????????error

# ??debug??,?????????????????????false
#debug: true

# ???????root???????????????
logging:
  # ????
  groups:
    ebank: com.shubao.controller,com.shubao.service,com.shubao.dao
    iservice: com.alibaba
  level:
    # ????????????
    root: info
    # ???????????
#    com.shubao.controller: debug
    # ???????????????
#    com.shubao.controller.user: debug
    ebank: warn

  # ??????
  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} %p %c{1}:%L - %m%n'
#    console: '%d - %m %n'
    console: '%d %clr(%5p) --- [%16t] %clr(%-40.40c){cyan} : %m %n'
  file:
    name: d:\\logs\springboot.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: d:\\logs\springboot-%d{yyyy-MM-dd}.%i.log