# ????
#   - trace ??????,????
#   - debug ?????????
#   - info ????????
#   - warn ??????????
#   - error ????????
#   - fatal ?????????error

# ??debug??,?????????????????????false
#debug: true

# ???????root???????????????
logging:
  # ????
  groups:
    ebank: com.shubao.controller,com.shubao.service,com.shubao.dao
    iservice: com.alibaba
  level:
    # ????????????
    root: info
    # ???????????
#    com.shubao.controller: debug
    # ???????????????
#    com.shubao.controller.user: debug
    ebank: warn
