# 2. 配置相关信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wollo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1106135
